# -*- coding: utf-8 -*-
"""004_VENDAS-FICTÍCIAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEBsZveBOVOgCKMs5DKX3vlxXqvrDzMr

## **BASE DE VENDAS FICTÍCIAS**

Problemas resolvidos:

    - Padronização das colunas
    - Conversão
    - Valores faltantes
    - Valores duplicados
    - Mensuramento dos dados
"""

import pandas as pd
import numpy as np

df = pd.read_csv('vendas_ficticias.csv')

# 5000 linhas e 7 colunas
df.shape

qtd_linhas = df.shape[0]
qtd_colunas = df.shape[1]

# padronização e conversão de Preço e Data_Venda
df.info()

# padronização das colunas
df.columns

colunas = ['id', 'produto', 'categoria', 'preco', 'quantidade', 'dt_venda',
       'vendedor']
df.columns = colunas

df.columns

# conversao de preco

df.preco

df['preco'] = df['preco'].str.replace("'",  '')
# df['preco'] = pd.to_numeric(df['preco'].str.replace("'", ''))

df.preco

df = df.astype(
    {
        'preco': np.float64
    }
)

df.preco

# conversão de data
df.dt_venda

df['dt_venda'] = pd.to_datetime(df['dt_venda'], format='%Y-%m-%d')

df.dt_venda

# valores faltantes
df.info()

# correção de valores faltantes em produto, categoria, vendedor e dt_venda
df.isnull().sum()

df['produto'] = df['produto'].fillna('Desconhecido')
df['categoria'] = df['categoria'].fillna('Desconhecida')
df['vendedor'] = df['vendedor'].fillna('Desconhecido')

df.info()

df['dt_venda'].fillna('2023-09-22', inplace=True)
df.info()

# não há duplicidade de dados
df.duplicated().sum()

df.columns
df['id'].duplicated().sum()

# criação de colunas
df['faturamento'] = df['preco'] * df['quantidade']
df['margem_contribuicao'] = df['faturamento'] / df['faturamento'].sum() * 100

df['mes'] = df['dt_venda'].dt.month
df['ano'] = df['dt_venda'].dt.year

df.head()

df.ano.unique()

df.mes.unique()

# mensuramento de dados
df_resumo = df.groupby(['ano', 'mes']).agg(
    {
        'quantidade': 'sum',
        'faturamento': 'sum'
    }
)

df_resumo.query("ano <= 2025")
